/**
 * @author generated by eTrice
 *
 * Source File of DataClass ADASMessage
 * 
 */

#include <string.h>

#include "ADASMessage.h"
#include "ADASMessage_Utils.h"



/*--------------------- operations ---------------------*/

void ADASMessage_deepCopy(ADASMessage* source, ADASMessage* target) {
	memcpy(target, source, sizeof(ADASMessage));
}


