/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AirMassFlowEntity
 *
 */

#ifndef _TEMPLATEMODEL_AIRMASSFLOWENTITY_H_
#define _TEMPLATEMODEL_AIRMASSFLOWENTITY_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec airmassstart,airmassend;
/*--------------------- end user code ---------------------*/

typedef struct AirMassFlowEntity AirMassFlowEntity;

/* const part of ActorClass (ROM) */
typedef struct AirMassFlowEntity_const {
	const char* instName;

	/* simple ports */
	const SendDataPort massflowdata;
	const SendDataConjPort massflowdatasend;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} AirMassFlowEntity_const;


/* constant for state machine data */
#define AIRMASSFLOWENTITY_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AirMassFlowEntity {
	const AirMassFlowEntity_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[AIRMASSFLOWENTITY_HISTORY_SIZE];
};

void AirMassFlowEntity_init(AirMassFlowEntity* self);

void AirMassFlowEntity_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_AIRMASSFLOWENTITY_H_ */

