/**
 * @author generated by eTrice
 *
 * Header File of ActorClass BassFuelMassEntity2
 *
 */

#ifndef _TEMPLATEMODEL_BASSFUELMASSENTITY2_H_
#define _TEMPLATEMODEL_BASSFUELMASSENTITY2_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec bassfuelstart2,bassfuelend2;
/*--------------------- end user code ---------------------*/

typedef struct BassFuelMassEntity2 BassFuelMassEntity2;

/* const part of ActorClass (ROM) */
typedef struct BassFuelMassEntity2_const {
	const char* instName;

	/* simple ports */
	const SendDataPort bassfueldata2;
	const SendDataConjPort bassfueldatasend2;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} BassFuelMassEntity2_const;


/* constant for state machine data */
#define BASSFUELMASSENTITY2_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct BassFuelMassEntity2 {
	const BassFuelMassEntity2_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[BASSFUELMASSENTITY2_HISTORY_SIZE];
};

void BassFuelMassEntity2_init(BassFuelMassEntity2* self);

void BassFuelMassEntity2_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_BASSFUELMASSENTITY2_H_ */

