/**
 * @author generated by eTrice
 *
 * Source File of ActorClass IgnitionSystem
 *
 */

#include "IgnitionSystem.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/timing/PTimer.h"
#include "TemplateModel/SendData.h"

#include "IgnitionSystem_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_airflowPort = 3,
	IFITEM_ignitiondata = 4,
	IFITEM_ignitionInternalIn = 1,
	IFITEM_ignitionInternalOut = 2,
	IFITEM_timer = 5
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_waitingData = 2,
	STATE_MAX = 3
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__waitingData = 1,
	CHAIN_TRANS_tr2_FROM_waitingData_TO_cp0_BY_sendDataairflowPort = 2,
	CHAIN_TRANS_tr3_FROM_waitingData_TO_waitingData_BY_timeouttimer_tr3 = 3,
	CHAIN_TRANS_tr4_FROM_waitingData_TO_waitingData_BY_sendDataignitionInternalOut_tr4 = 4
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_ignitionInternalIn__recursive2 = IFITEM_ignitionInternalIn + EVT_SHIFT*SendData_OUT_recursive2,
	TRIG_ignitionInternalIn__recvchangestate = IFITEM_ignitionInternalIn + EVT_SHIFT*SendData_OUT_recvchangestate,
	TRIG_ignitionInternalOut__sendData = IFITEM_ignitionInternalOut + EVT_SHIFT*SendData_IN_sendData,
	TRIG_ignitionInternalOut__sendchangestate = IFITEM_ignitionInternalOut + EVT_SHIFT*SendData_IN_sendchangestate,
	TRIG_airflowPort__sendData = IFITEM_airflowPort + EVT_SHIFT*SendData_IN_sendData,
	TRIG_airflowPort__sendchangestate = IFITEM_airflowPort + EVT_SHIFT*SendData_IN_sendchangestate,
	TRIG_ignitiondata__recursive2 = IFITEM_ignitiondata + EVT_SHIFT*SendData_OUT_recursive2,
	TRIG_ignitiondata__recvchangestate = IFITEM_ignitiondata + EVT_SHIFT*SendData_OUT_recvchangestate,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","waitingData"
};

static void setState(IgnitionSystem* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(IgnitionSystem* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__waitingData(IgnitionSystem* self) {
    count=1;
    fp8 = fopen("MassAir_ignition.txt", "a");
    timer_startTimer(10);
}
static void action_TRANS_tr2_FROM_waitingData_TO_cp0_BY_sendDataairflowPort(IgnitionSystem* self, const InterfaceItemBase* ifitem, ADASMessage* data) {
    if(CHECKTIME==10||CHECKTIME==31){
    clock_gettime(CLOCK_MONOTONIC,&airflowstart);
    pthread_t id;
    id=pthread_self();
    
    actor3_2_id=(int)id;
    }
    for(int i =0;i<ONE_Milli_SEC_CONUT*0.03;i++){
    }
    actor3_1_id = data->actor_1_id;
    recvairflowsensetime=data->actor_1;//WCET of MassairflowSensor runnable
    airflowscen = data->scenarioID;
    airflowins = data->instanceID;
}
static void action_TRANS_tr3_FROM_waitingData_TO_waitingData_BY_timeouttimer_tr3(IgnitionSystem* self, const InterfaceItemBase* ifitem) {
    ADASMessage ADASmessage;
    if(CHECKTIME==15||CHECKTIME==16||CHECKTIME==30||CHECKTIME==31){
    clock_gettime(CLOCK_MONOTONIC,&ignistart);
    ADASmessage.actor_1 = ((1.0e+9*ignistart.tv_sec)+ignistart.tv_nsec)/1.0e+6;
    pthread_t id;
    id=pthread_self();
    ADASmessage.actor_1_id=(int)id;
    }
    for(int i =0;i<ONE_Milli_SEC_CONUT*0.05*MULCCS;i++){
    }
    ADASmessage.instanceID = count;
    //ADASmessage.prior=4;
    ignitionInternalIn_sendData(&ADASmessage);
    count++;
    //if(count==10000)
    //timer.kill();
}
static void action_TRANS_tr4_FROM_waitingData_TO_waitingData_BY_sendDataignitionInternalOut_tr4(IgnitionSystem* self, const InterfaceItemBase* ifitem, ADASMessage* data) {
    ADASMessage ADASmessage;
    clock_gettime(CLOCK_MONOTONIC,&ignistart2);
    ADASmessage.actor_4 = ((1.0e+9*(ignistart2.tv_sec))+(ignistart2.tv_nsec))/1.0e+6;
    pthread_t id;
    id=pthread_self();
    ADASmessage.actor_4_id=(int)id;
    ADASmessage.scenarioID=7;
    ADASmessage.instanceID=data->instanceID;
    ADASmessage.actor_1 = data->actor_1;
    ADASmessage.actor_2 =data->actor_2;
    ADASmessage.actor_3=data->actor_3;
    ADASmessage.actor_1_id=data->actor_1_id;
    ADASmessage.actor_2_id=data->actor_2_id;
    ADASmessage.actor_3_id=data->actor_3_id;
    //ADASmessage.prior=4;
    ADASmessage.staticcheck = 1;	//added by kkr for global actor
    ignitiondata_sendData(&ADASmessage);
}
static void action_TRANS_tr1_FROM_cp0_TO_waitingData_COND_tr1(IgnitionSystem* self, const InterfaceItemBase* ifitem, ADASMessage* data) {
    clock_gettime(CLOCK_MONOTONIC,&airflowend);
    //changePriority(pthread_self(),&self->constData->airflowPort.msgService->messageQueue);
    if(CHECKTIME==9||CHECKTIME==30){
    fprintf(fp8, "scenarionum: %d, instancenum: %d, totaltime:%f\n",airflowscen,airflowins, ((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)-recvairflowsensetime));
    }
    else if(CHECKTIME==10||CHECKTIME==31){
    //fprintf(fp8, "scenarionum: %d, instancenum: %d,airflowsensor:%f, ignisys:%f, totaltime:%f\n",airflowscen,airflowins, recvairflowsensetime,((1.0e+9*(airflowstart.tv_sec))+(airflowstart.tv_nsec))/1.0e+6,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)-recvairflowsensetime));
    fprintf(fp8, "%5.6f,scenario_3,%d,instance_%d,actor_3,%f\n%f,scenario_3,%d,instance_%d,actor_7,%f\n",recvairflowsensetime,actor3_1_id,airflowins,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)),((1.0e+9*(airflowstart.tv_sec))+(airflowstart.tv_nsec))/1.0e+6,actor3_2_id,airflowins,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)));
    }
    fclose(fp8);
}
static void action_TRANS_tr6_FROM_cp0_TO_waitingData_COND_tr6(IgnitionSystem* self, const InterfaceItemBase* ifitem, ADASMessage* data) {
    clock_gettime(CLOCK_MONOTONIC,&airflowend);
    //changePriority(pthread_self(),&self->constData->airflowPort.msgService->messageQueue);
    
    if(CHECKTIME==9||CHECKTIME==30){
    fprintf(fp8, "scenarionum: %d, instancenum: %d, totaltime:%f\n",airflowscen,airflowins, ((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)-recvairflowsensetime));
    }
    else if(CHECKTIME==10||CHECKTIME==31){
    //fprintf(fp8, "scenarionum: %d, instancenum: %d,airflowsensor:%f, ignisys:%f, totaltime:%f\n",airflowscen,airflowins, recvairflowsensetime,((1.0e+9*(airflowstart.tv_sec))+(airflowstart.tv_nsec))/1.0e+6,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)-recvairflowsensetime));
    fprintf(fp8, "%5.6f,scenario_3,%d,instance_%d,actor_3,%f\n%f,scenario_3,%d,instance_%d,actor_7,%f\n",recvairflowsensetime,actor3_1_id,airflowins,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)),((1.0e+9*(airflowstart.tv_sec))+(airflowstart.tv_nsec))/1.0e+6,actor3_2_id,airflowins,((((1.0e+9*airflowend.tv_sec)+airflowend.tv_nsec)/1.0e+6)));
    }
    fflush(fp8);
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(IgnitionSystem* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_waitingData:
				self->history[STATE_TOP] = STATE_waitingData;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(IgnitionSystem* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__waitingData:
		{
			action_TRANS_INITIAL_TO__waitingData(self);
			return STATE_waitingData;
		}
		case CHAIN_TRANS_tr2_FROM_waitingData_TO_cp0_BY_sendDataairflowPort:
		{
			ADASMessage* data = ((ADASMessage*) generic_data__et);
			action_TRANS_tr2_FROM_waitingData_TO_cp0_BY_sendDataairflowPort(self, ifitem, data);
			if (airflowins==10000) {
			action_TRANS_tr1_FROM_cp0_TO_waitingData_COND_tr1(self, ifitem, data);
			return STATE_waitingData;}
			else if (airflowemer==1) {
			return STATE_waitingData;}
			else if (airflowins<10000&&airflowins>0) {
			action_TRANS_tr6_FROM_cp0_TO_waitingData_COND_tr6(self, ifitem, data);
			return STATE_waitingData;}
			else {
			return STATE_waitingData;}
		}
		case CHAIN_TRANS_tr3_FROM_waitingData_TO_waitingData_BY_timeouttimer_tr3:
		{
			action_TRANS_tr3_FROM_waitingData_TO_waitingData_BY_timeouttimer_tr3(self, ifitem);
			return STATE_waitingData;
		}
		case CHAIN_TRANS_tr4_FROM_waitingData_TO_waitingData_BY_sendDataignitionInternalOut_tr4:
		{
			ADASMessage* data = ((ADASMessage*) generic_data__et);
			action_TRANS_tr4_FROM_waitingData_TO_waitingData_BY_sendDataignitionInternalOut_tr4(self, ifitem, data);
			return STATE_waitingData;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(IgnitionSystem* self, etInt16 state__et) {
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_waitingData:
				/* in leaf state: return state id */
				return STATE_waitingData;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void IgnitionSystem_executeInitTransition(IgnitionSystem* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__waitingData;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void IgnitionSystem_receiveEventInternal(IgnitionSystem* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
		    case STATE_waitingData:
		        switch(trigger__et) {
		                case TRIG_airflowPort__sendData:
		                    {
		                        chain__et = CHAIN_TRANS_tr2_FROM_waitingData_TO_cp0_BY_sendDataairflowPort;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                case TRIG_timer__timeout:
		                    {
		                        chain__et = CHAIN_TRANS_tr3_FROM_waitingData_TO_waitingData_BY_timeouttimer_tr3;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                case TRIG_ignitionInternalOut__sendData:
		                    {
		                        chain__et = CHAIN_TRANS_tr4_FROM_waitingData_TO_waitingData_BY_sendDataignitionInternalOut_tr4;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    default:
		        /* should not occur */
		        break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void IgnitionSystem_receiveEvent(IgnitionSystem* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	IgnitionSystem_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void IgnitionSystem_init(IgnitionSystem* self){
	ET_MSC_LOGGER_SYNC_ENTRY("IgnitionSystem", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<IGNITIONSYSTEM_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	IgnitionSystem_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void IgnitionSystem_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("IgnitionSystem", "_receiveMessage")
	IgnitionSystem_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

