/**
 * @author generated by eTrice
 *
 * Header File of ActorClass InjectionTimingActuatorEntity
 *
 */

#ifndef _TEMPLATEMODEL_INJECTIONTIMINGACTUATORENTITY_H_
#define _TEMPLATEMODEL_INJECTIONTIMINGACTUATORENTITY_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec injectactstart,injectactend;
/*--------------------- end user code ---------------------*/

typedef struct InjectionTimingActuatorEntity InjectionTimingActuatorEntity;

/* const part of ActorClass (ROM) */
typedef struct InjectionTimingActuatorEntity_const {
	const char* instName;

	/* simple ports */
	const SendDataPort Injectionactordata;
	const SendDataConjPort Injectionactordatasend;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} InjectionTimingActuatorEntity_const;


/* constant for state machine data */
#define INJECTIONTIMINGACTUATORENTITY_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct InjectionTimingActuatorEntity {
	const InjectionTimingActuatorEntity_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[INJECTIONTIMINGACTUATORENTITY_HISTORY_SIZE];
};

void InjectionTimingActuatorEntity_init(InjectionTimingActuatorEntity* self);

void InjectionTimingActuatorEntity_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_INJECTIONTIMINGACTUATORENTITY_H_ */

