/**
 * @author generated by eTrice
 *
 * Header File of ProtocolClass SendData
 * 
 */

#ifndef _TEMPLATEMODEL_SENDDATA_H_
#define _TEMPLATEMODEL_SENDDATA_H_

#include "etDatatypes.h"
#include "modelbase/etPort.h"


/* include all referenced room classes */
#include "TemplateModel/ADASMessage.h"


/* message IDs */
enum SendData_msg_ids {
	SendData_MSG_MIN = 0,
	SendData_OUT_recursive2 = 1,
	SendData_OUT_recvchangestate = 2,
	SendData_IN_sendData = 3,
	SendData_IN_sendchangestate = 4,
	SendData_MSG_MAX = 5
};

/*--------------------- port structs and methods */
typedef etPort SendDataPort;
typedef etReplPort SendDataReplPort;


void SendDataPort_recursive2(const SendDataPort* self, ADASMessage* data);
void SendDataReplPort_recursive2_broadcast(const SendDataReplPort* self, ADASMessage* data);
void SendDataReplPort_recursive2(const SendDataReplPort* self, int idx, ADASMessage* data);
void SendDataPort_recvchangestate(const SendDataPort* self);
void SendDataReplPort_recvchangestate_broadcast(const SendDataReplPort* self);
void SendDataReplPort_recvchangestate(const SendDataReplPort* self, int idx);


etInt32 SendDataReplPort_getReplication(const SendDataReplPort* self);
typedef etPort SendDataConjPort;
typedef etReplPort SendDataConjReplPort;


void SendDataConjPort_sendData(const SendDataConjPort* self, ADASMessage* data);
void SendDataConjReplPort_sendData_broadcast(const SendDataConjReplPort* self, ADASMessage* data);
void SendDataConjReplPort_sendData(const SendDataConjReplPort* self, int idx, ADASMessage* data);
void SendDataConjPort_sendchangestate(const SendDataConjPort* self);
void SendDataConjReplPort_sendchangestate_broadcast(const SendDataConjReplPort* self);
void SendDataConjReplPort_sendchangestate(const SendDataConjReplPort* self, int idx);


etInt32 SendDataConjReplPort_getReplication(const SendDataConjReplPort* self);

/*--------------------- debug helpers */

/* get message string for message id */
const char* SendData_getMessageString(int msg_id);


#endif /* _TEMPLATEMODEL_SENDDATA_H_ */

