/**
 * @author generated by eTrice
 *
 * Header File of ActorClass throttlecontroller
 *
 */

#ifndef _TEMPLATEMODEL_THROTTLECONTROLLER_H_
#define _TEMPLATEMODEL_THROTTLECONTROLLER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec throcontrolstart,throcontrolend;
/*--------------------- end user code ---------------------*/

typedef struct throttlecontroller throttlecontroller;

/* const part of ActorClass (ROM) */
typedef struct throttlecontroller_const {
	const char* instName;

	/* simple ports */
	const SendDataPort throttledata;
	const SendDataConjPort throttledatasend;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} throttlecontroller_const;


/* constant for state machine data */
#define THROTTLECONTROLLER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct throttlecontroller {
	const throttlecontroller_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 float64 recvthrottlesensetime;
	 float64 recvfirsttime;
	 float64 recvpedalsensetime;
	 float64 recvairsystemstarttime;


	/* state machine variables */
	etInt16 state;
	etInt16 history[THROTTLECONTROLLER_HISTORY_SIZE];
};

void throttlecontroller_init(throttlecontroller* self);

void throttlecontroller_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_THROTTLECONTROLLER_H_ */

