/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ThrottleSensor
 *
 */

#ifndef _TEMPLATEMODEL_THROTTLESENSOR_H_
#define _TEMPLATEMODEL_THROTTLESENSOR_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec throttlesensestart,throttlesenseend;
/*--------------------- end user code ---------------------*/

typedef struct ThrottleSensor ThrottleSensor;

/* const part of ActorClass (ROM) */
typedef struct ThrottleSensor_const {
	const char* instName;

	/* simple ports */
	const SendDataConjPort throttledata;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} ThrottleSensor_const;


/* constant for state machine data */
#define THROTTLESENSOR_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct ThrottleSensor {
	const ThrottleSensor_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int64 count;


	/* state machine variables */
	etInt16 state;
	etInt16 history[THROTTLESENSOR_HISTORY_SIZE];
};

void ThrottleSensor_init(ThrottleSensor* self);

void ThrottleSensor_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_THROTTLESENSOR_H_ */

