/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ATcpServer
 *
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_ATCPSERVER_H_
#define _ROOM_BASIC_SERVICE_TCP_ATCPSERVER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "room/basic/service/tcp/DTcpPayload.h"
#include "room/basic/service/tcp/PTcpControl.h"
#include "room/basic/service/tcp/PTcpPayload.h"

/*--------------------- begin user code ---------------------*/
#include "osal/etTcpSockets.h"
/*--------------------- end user code ---------------------*/

typedef struct ATcpServer ATcpServer;

/* const part of ActorClass (ROM) */
typedef struct ATcpServer_const {
	const char* instName;

	/* simple ports */
	const PTcpControlPort controlPort;
	const PTcpPayloadPort payloadPort;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} ATcpServer_const;


/* constant for state machine data */
#define ATCPSERVER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct ATcpServer {
	const ATcpServer_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int32 lastError;
	 DTcpPayload payloadRecvBuffer;
	 etSocketServerData* server;


	/* state machine variables */
	etInt16 state;
	etInt16 history[ATCPSERVER_HISTORY_SIZE];
};

void ATcpServer_init(ATcpServer* self);

void ATcpServer_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/
 void ATcpServer_ctor(ATcpServer* self);
 void ATcpServer_dtor(ATcpServer* self);

/*--------------------- operations ---------------------*/
 bool ATcpServer_hasError(ATcpServer* self);
 void ATcpServer_setErrorCode(ATcpServer* self, int32 value);


#endif /* _ROOM_BASIC_SERVICE_TCP_ATCPSERVER_H_ */

