/**
 * @author generated by eTrice
 *
 * Utils File of DataClass DTcpControl
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_UTILS_H_
#define _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_UTILS_H_

#include "room/basic/service/tcp/DTcpControl.h"

/*
 * access macros for operations and attributes
*/

/* operations */

/* attributes */
#define IPAddr (self->IPAddr)
#define TcpPort (self->TcpPort)

#endif /* _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_UTILS_H_ */

