/**
 * @author generated by eTrice
 *
 * Source File of DataClass DTcpPayload
 * 
 */

#include <string.h>

#include "DTcpPayload.h"
#include "DTcpPayload_Utils.h"



/*--------------------- operations ---------------------*/
 int32 DTcpPayload_getMaxLength(DTcpPayload* self) {
	return 32;
}
 void DTcpPayload_setAsString(DTcpPayload* self, charPtr value) {
	/* used macros: data, length */
	int valLength = (strlen(value)+1 > 32)? 32 : strlen(value) + 1;
	memcpy(data, value, valLength);
	data[31] = '\0';
	length = valLength;
}
 void DTcpPayload_setData(DTcpPayload* self, int8* value, int32 size) {
	/* used macros: data, length */
	strncpy(data, value, ((size>32)?32:size));
	length = size;
}
 charPtr DTcpPayload_getAsString(DTcpPayload* self) {
	/* used macros: data */
	data[31] = '\0';
	return data;
}

void DTcpPayload_deepCopy(DTcpPayload* source, DTcpPayload* target) {
	memcpy(target, source, sizeof(DTcpPayload));
}


