/**
 * @author generated by eTrice
 *
 * Header File of DataClass DTcpPayload
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_DTCPPAYLOAD_H_
#define _ROOM_BASIC_SERVICE_TCP_DTCPPAYLOAD_H_

#include "etDatatypes.h"


		
typedef struct {
	/*--------------------- attributes ---------------------*/
	 int32 connectionId;
	 int32 length;
	 int8 data[32]
	;
} DTcpPayload;



/*--------------------- operations ---------------------*/
 int32 DTcpPayload_getMaxLength(DTcpPayload* self);
 void DTcpPayload_setAsString(DTcpPayload* self, charPtr value);
 void DTcpPayload_setData(DTcpPayload* self, int8* value, int32 size);
 charPtr DTcpPayload_getAsString(DTcpPayload* self);

/* deep copy */
void DTcpPayload_deepCopy(DTcpPayload* source, DTcpPayload* target);


#endif /* _ROOM_BASIC_SERVICE_TCP_DTCPPAYLOAD_H_ */

