/**
 * @author generated by eTrice
 *
 * Source File of DataClass DTcpControl
 * 
 */

#include <string.h>

#include "DTcpControl.h"
#include "DTcpControl_Utils.h"



/*--------------------- operations ---------------------*/

void DTcpControl_deepCopy(DTcpControl* source, DTcpControl* target) {
	memcpy(target, source, sizeof(DTcpControl));
}


