/**
 * @author generated by eTrice
 *
 * Header File of DataClass DTcpControl
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_H_
#define _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_H_

#include "etDatatypes.h"


		
typedef struct {
	/*--------------------- attributes ---------------------*/
	 charPtr IPAddr;
	 int32 TcpPort;
} DTcpControl;



/*--------------------- operations ---------------------*/

/* deep copy */
void DTcpControl_deepCopy(DTcpControl* source, DTcpControl* target);


#endif /* _ROOM_BASIC_SERVICE_TCP_DTCPCONTROL_H_ */

