/**
 * @author generated by eTrice
 *
 * Header File of ProtocolClass PTcpControl
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_PTCPCONTROL_H_
#define _ROOM_BASIC_SERVICE_TCP_PTCPCONTROL_H_

#include "etDatatypes.h"
#include "modelbase/etPort.h"


#include "room/basic/service/tcp/DTcpControl.h"


/* message IDs */
enum PTcpControl_msg_ids {
	PTcpControl_MSG_MIN = 0,
	PTcpControl_OUT_connected = 1,
	PTcpControl_OUT_disconnected = 2,
	PTcpControl_OUT_error = 3,
	PTcpControl_IN_connect = 4,
	PTcpControl_IN_disconnect = 5,
	PTcpControl_MSG_MAX = 6
};

/*--------------------- port structs and methods */
typedef etPort PTcpControlPort;
typedef etReplPort PTcpControlReplPort;


void PTcpControlPort_connected(const PTcpControlPort* self);
void PTcpControlReplPort_connected_broadcast(const PTcpControlReplPort* self);
void PTcpControlReplPort_connected(const PTcpControlReplPort* self, int idx);
void PTcpControlPort_disconnected(const PTcpControlPort* self);
void PTcpControlReplPort_disconnected_broadcast(const PTcpControlReplPort* self);
void PTcpControlReplPort_disconnected(const PTcpControlReplPort* self, int idx);
void PTcpControlPort_error(const PTcpControlPort* self);
void PTcpControlReplPort_error_broadcast(const PTcpControlReplPort* self);
void PTcpControlReplPort_error(const PTcpControlReplPort* self, int idx);


etInt32 PTcpControlReplPort_getReplication(const PTcpControlReplPort* self);
typedef etPort PTcpControlConjPort;
typedef etReplPort PTcpControlConjReplPort;


void PTcpControlConjPort_connect(const PTcpControlConjPort* self, DTcpControl* data);
void PTcpControlConjReplPort_connect_broadcast(const PTcpControlConjReplPort* self, DTcpControl* data);
void PTcpControlConjReplPort_connect(const PTcpControlConjReplPort* self, int idx, DTcpControl* data);
void PTcpControlConjPort_disconnect(const PTcpControlConjPort* self);
void PTcpControlConjReplPort_disconnect_broadcast(const PTcpControlConjReplPort* self);
void PTcpControlConjReplPort_disconnect(const PTcpControlConjReplPort* self, int idx);


etInt32 PTcpControlConjReplPort_getReplication(const PTcpControlConjReplPort* self);

/*--------------------- debug helpers */

/* get message string for message id */
const char* PTcpControl_getMessageString(int msg_id);


#endif /* _ROOM_BASIC_SERVICE_TCP_PTCPCONTROL_H_ */

