/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AccelPedalDiagEntity
 *
 */

#include "AccelPedalDiagEntity.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/timing/PTimer.h"

#include "AccelPedalDiagEntity_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_timer = 1
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_SenseData = 2,
	STATE_MAX = 3
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__SenseData = 1,
	CHAIN_TRANS_tr0_FROM_SenseData_TO_SenseData_BY_timeouttimer_tr0 = 2
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","SenseData"
};

static void setState(AccelPedalDiagEntity* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(AccelPedalDiagEntity* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__SenseData(AccelPedalDiagEntity* self) {
    timer_startTimer(100);
    fp = fopen("Pedaldiag.txt", "a");
    count=1;
}
static void action_TRANS_tr0_FROM_SenseData_TO_SenseData_BY_timeouttimer_tr0(AccelPedalDiagEntity* self, const InterfaceItemBase* ifitem) {
    if(CHECKTIME==19||CHECKTIME==20||CHECKTIME==30||CHECKTIME==31){
    clock_gettime(CLOCK_MONOTONIC,&diagstart);
    pthread_t id;
    id=pthread_self();
    actor4_1_id=(int)id;
    }
    for(int i =0;i<ONE_Milli_SEC_CONUT*0.235*MULCCS;i++){
    }
    if(CHECKTIME==19||CHECKTIME==20||CHECKTIME==30||CHECKTIME==31&&count>0&&count<10000){
    clock_gettime(CLOCK_MONOTONIC,&diagend);
    //fprintf(fp, "pedalDiag:%f\n",((1.0e+9*(diagend.tv_sec-diagstart.tv_sec))+(diagend.tv_nsec-diagstart.tv_nsec))/1.0e+6);
    fprintf(fp, "%5.6f,scenario_4,%d,instance_%d,actor_4,%f\n",((1.0e+9*(diagstart.tv_sec))+(diagstart.tv_nsec))/1.0e+6,actor4_1_id,count,((1.0e+9*(diagend.tv_sec))+(diagend.tv_nsec))/1.0e+6);
    fflush (fp);
    }
    if(count==1000){
    clock_gettime(CLOCK_MONOTONIC,&diagend);
    //fprintf(fp, "pedalDiag:%f\n",((1.0e+9*(diagend.tv_sec-diagstart.tv_sec))+(diagend.tv_nsec-diagstart.tv_nsec))/1.0e+6);
    fprintf(fp, "%5.6f,scenario_4,%d,instance_%d,actor_4,%f\n",((1.0e+9*(diagstart.tv_sec))+(diagstart.tv_nsec))/1.0e+6,actor4_1_id,count,((1.0e+9*(diagend.tv_sec))+(diagend.tv_nsec))/1.0e+6);
    fclose(fp);
    }
    count++;
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(AccelPedalDiagEntity* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_SenseData:
				self->history[STATE_TOP] = STATE_SenseData;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AccelPedalDiagEntity* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__SenseData:
		{
			action_TRANS_INITIAL_TO__SenseData(self);
			return STATE_SenseData;
		}
		case CHAIN_TRANS_tr0_FROM_SenseData_TO_SenseData_BY_timeouttimer_tr0:
		{
			action_TRANS_tr0_FROM_SenseData_TO_SenseData_BY_timeouttimer_tr0(self, ifitem);
			return STATE_SenseData;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AccelPedalDiagEntity* self, etInt16 state__et) {
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_SenseData:
				/* in leaf state: return state id */
				return STATE_SenseData;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AccelPedalDiagEntity_executeInitTransition(AccelPedalDiagEntity* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__SenseData;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AccelPedalDiagEntity_receiveEventInternal(AccelPedalDiagEntity* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
		    case STATE_SenseData:
		        switch(trigger__et) {
		                case TRIG_timer__timeout:
		                    {
		                        chain__et = CHAIN_TRANS_tr0_FROM_SenseData_TO_SenseData_BY_timeouttimer_tr0;
		                        catching_state__et = STATE_TOP;
		                    }
		                break;
		                default:
		                    /* should not occur */
		                    break;
		        }
		        break;
		    default:
		        /* should not occur */
		        break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void AccelPedalDiagEntity_receiveEvent(AccelPedalDiagEntity* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	AccelPedalDiagEntity_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void AccelPedalDiagEntity_init(AccelPedalDiagEntity* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AccelPedalDiagEntity", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ACCELPEDALDIAGENTITY_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AccelPedalDiagEntity_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AccelPedalDiagEntity_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AccelPedalDiagEntity", "_receiveMessage")
	AccelPedalDiagEntity_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

