/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass AccelPedalSensor
 *
 */

#ifndef _TEMPLATEMODEL_ACCELPEDALSENSOR_UTILS_H_
#define _TEMPLATEMODEL_ACCELPEDALSENSOR_UTILS_H_

#include "TemplateModel/AccelPedalSensor.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define pedaldata_sendData(data) SendDataConjPort_sendData(&self->constData->pedaldata, data)
#define pedaldata_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->pedaldata)

/* data receive ports */

/* data send ports */

/* saps */
#define timer_startTimer(data) PTimerConjPort_startTimer(&self->constData->timer, data)
#define timer_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->timer, data)
#define timer_kill() PTimerConjPort_kill(&self->constData->timer)

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define count (self->count)

/* port operations */

#endif /* _TEMPLATEMODEL_ACCELPEDALSENSOR_UTILS_H_ */

