/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass CylinerNumObserver
 *
 */

#ifndef _TEMPLATEMODEL_CYLINERNUMOBSERVER_UTILS_H_
#define _TEMPLATEMODEL_CYLINERNUMOBSERVER_UTILS_H_

#include "TemplateModel/CylinerNumObserver.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define cylinernum1Port_recursive2(data) SendDataPort_recursive2(&self->constData->cylinernum1Port, data)
#define cylinernum1Port_recvchangestate() SendDataPort_recvchangestate(&self->constData->cylinernum1Port)
#define cylinernum2Port_recursive2(data) SendDataPort_recursive2(&self->constData->cylinernum2Port, data)
#define cylinernum2Port_recvchangestate() SendDataPort_recvchangestate(&self->constData->cylinernum2Port)

/* data receive ports */

/* data send ports */

/* saps */
#define timer_startTimer(data) PTimerConjPort_startTimer(&self->constData->timer, data)
#define timer_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->timer, data)
#define timer_kill() PTimerConjPort_kill(&self->constData->timer)

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TEMPLATEMODEL_CYLINERNUMOBSERVER_UTILS_H_ */

