/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass pedalvoter
 *
 */

#ifndef _TEMPLATEMODEL_PEDALVOTER_UTILS_H_
#define _TEMPLATEMODEL_PEDALVOTER_UTILS_H_

#include "TemplateModel/pedalvoter.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define pedalvoterdata_recursive2(data) SendDataPort_recursive2(&self->constData->pedalvoterdata, data)
#define pedalvoterdata_recvchangestate() SendDataPort_recvchangestate(&self->constData->pedalvoterdata)
#define feeldata_sendData(data) SendDataConjPort_sendData(&self->constData->feeldata, data)
#define feeldata_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->feeldata)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define recvthrottlesensetime (self->recvthrottlesensetime)
#define recvfirsttime (self->recvfirsttime)
#define recvpedalsensetime (self->recvpedalsensetime)
#define recvairsystemstarttime (self->recvairsystemstarttime)

/* port operations */

#endif /* _TEMPLATEMODEL_PEDALVOTER_UTILS_H_ */

