/**
 * @author generated by eTrice
 *
 * Header File of DataClass ADASMessage
 * 
 */

#ifndef _TEMPLATEMODEL_ADASMESSAGE_H_
#define _TEMPLATEMODEL_ADASMESSAGE_H_

#include "etDatatypes.h"

/* include all referenced room classes */

		
typedef struct {
	/*--------------------- attributes ---------------------*/
	 int8 scenarioID;
	 int32 instanceID;
	 float64 actor_1;
	 float64 actor_2;
	 float64 actor_3;
	 float64 actor_4;
	 float64 actor_5;
	 float64 actor_6;
	 int32 actor_1_id;
	 int32 actor_2_id;
	 int32 actor_3_id;
	 int32 actor_4_id;
	 int32 actor_5_id;
	 int32 actor_6_id;
	 int8 emergency;
	 int8 prior;
	 int8 staticcheck;
} ADASMessage;



/*--------------------- operations ---------------------*/

/* deep copy */
void ADASMessage_deepCopy(ADASMessage* source, ADASMessage* target);


#endif /* _TEMPLATEMODEL_ADASMESSAGE_H_ */

