/**
 * @author generated by eTrice
 *
 * Header File of ActorClass IgnitionTimingEntity
 *
 */

#ifndef _TEMPLATEMODEL_IGNITIONTIMINGENTITY_H_
#define _TEMPLATEMODEL_IGNITIONTIMINGENTITY_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec ignitimestart,ignitimeend;
/*--------------------- end user code ---------------------*/

typedef struct IgnitionTimingEntity IgnitionTimingEntity;

/* const part of ActorClass (ROM) */
typedef struct IgnitionTimingEntity_const {
	const char* instName;

	/* simple ports */
	const SendDataPort ignitiontimingdata;
	const SendDataConjPort ignitiontimingdatasend;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} IgnitionTimingEntity_const;


/* constant for state machine data */
#define IGNITIONTIMINGENTITY_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct IgnitionTimingEntity {
	const IgnitionTimingEntity_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[IGNITIONTIMINGENTITY_HISTORY_SIZE];
};

void IgnitionTimingEntity_init(IgnitionTimingEntity* self);

void IgnitionTimingEntity_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_IGNITIONTIMINGENTITY_H_ */

