/**
 * @author generated by eTrice
 *
 * this class contains the main function running Node node with SubSystem subSystemRef
 * it instantiates Node node with SubSystem subSystemRef and starts and ends the lifecycle
 */

#include <string.h>

#include "node_subSystemRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"

#include "osal/etPlatformLifecycle.h"

/**
 * main function
 * creates components and starts and stops the lifecycle
 */

int main(int argc, char** argv) {
	etBool runAsTest = ET_FALSE;

#ifdef ET_DO_NOT_USE_ARGC_ARGV
#else
	if (argc>1 && strcmp(argv[1], "-headless")==0)
		runAsTest = ET_TRUE;
	if (argc>1 && strcmp(argv[1], "-run_as_test")==0)
		runAsTest = ET_TRUE;
#endif		

	etUserEntry(); /* platform specific */
	
	etLogger_logInfo("***   T H E   B E G I N   ***");
	ET_MSC_LOGGER_OPEN("main");

	/* startup sequence  of lifecycle */
	node_subSystemRef_init(); 		/* lifecycle init */
	node_subSystemRef_start(); 	/* lifecycle start */

	etUserPreRun(); /* platform specific */

	/* run Scheduler */
	node_subSystemRef_run(runAsTest);

	etUserPostRun(); /* platform specific */

	/* shutdown sequence of lifecycle */
	node_subSystemRef_stop(); 		/* lifecycle stop */
	node_subSystemRef_destroy(); 	/* lifecycle destroy */

	ET_MSC_LOGGER_CLOSE
	etLogger_logInfo("***   T H E   E N D   ***");

	etUserExit(); /* platform specific */

	return 0;
}

