/**
 * @author generated by eTrice
 *
 * Header File of ActorClass pedalvoter
 *
 */

#ifndef _TEMPLATEMODEL_PEDALVOTER_H_
#define _TEMPLATEMODEL_PEDALVOTER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec voterstart,voterend;
/*--------------------- end user code ---------------------*/

typedef struct pedalvoter pedalvoter;

/* const part of ActorClass (ROM) */
typedef struct pedalvoter_const {
	const char* instName;

	/* simple ports */
	const SendDataPort pedalvoterdata;
	const SendDataConjPort feeldata;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} pedalvoter_const;


/* constant for state machine data */
#define PEDALVOTER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct pedalvoter {
	const pedalvoter_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 float64 recvthrottlesensetime;
	 float64 recvfirsttime;
	 float64 recvpedalsensetime;
	 float64 recvairsystemstarttime;


	/* state machine variables */
	etInt16 state;
	etInt16 history[PEDALVOTER_HISTORY_SIZE];
};

void pedalvoter_init(pedalvoter* self);

void pedalvoter_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_PEDALVOTER_H_ */

