/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ATimingService
 *
 */

#include "ATimingService.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/timing/PTimer.h"

#include "ATimingService_Utils.h"

/*--------------------- begin user code ---------------------*/
/*uc3*/
/*--------------------- end user code ---------------------*/

/* interface item IDs */
enum interface_items {
	IFITEM_timer = 1
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_Operational = 2,
	STATE_MAX = 3
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__Operational = 1,
	CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_startTimeouttimer_tr1 = 2,
	CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_startTimertimer_tr3 = 3,
	CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4 = 4
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_timer__startTimer = IFITEM_timer + EVT_SHIFT*PTimer_IN_startTimer,
	TRIG_timer__startTimeout = IFITEM_timer + EVT_SHIFT*PTimer_IN_startTimeout,
	TRIG_timer__kill = IFITEM_timer + EVT_SHIFT*PTimer_IN_kill
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","Operational"
};

static void setState(ATimingService* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(ATimingService* self) {
	return self->state;
}

/* Entry and Exit Codes */
static void entry_Operational(ATimingService* self) {
	/* prepare */
}
static  void do_Operational(ATimingService* self) {
	/* maintain timers */
	etTimerControlBlock* temp;
	etTime t;
	
	getTimeFromTarget(&t);
	while (usedTcbsRoot !=0 ){
		if (isTimeGreater(&t,&(usedTcbsRoot->expTime))){
			timer_timeout(usedTcbsRoot->portIdx);
			temp=usedTcbsRoot;
			usedTcbsRoot=usedTcbsRoot->next;
			if((temp->pTime.sec==0)&&(temp->pTime.nSec==0)){
				/* single shot timer */
				returnTcb(temp);
			}else{
				/* periodic timer */
				addTime(&temp->expTime,&temp->pTime);
				putTcbToUsedList(temp);
				}
			}else{
				break;
				}
		}
}

/* Action Codes */
static void action_TRANS_INITIAL_TO__Operational(ATimingService* self) {
    int i;
    usedTcbsRoot=0;
    freeTcbsRoot=&tcbs[0];
    tcbs[ET_NB_OF_TCBS-1].next=0;
    for (i=0;i<ET_NB_OF_TCBS-1;i++){
    	tcbs[i].next=&tcbs[i+1];
    	}
}
static void action_TRANS_tr1_FROM_Operational_TO_Operational_BY_startTimeouttimer_tr1(ATimingService* self, const InterfaceItemBase* ifitem, uint32 time) {
    etTimerControlBlock* timer = getTcb();
    etTime t;
    if (timer!= 0){
    	t.sec=time/1000;
    	t.nSec=(time%1000)*1000000L;
    	timer->pTime.sec = 0;
    	timer->pTime.nSec = 0;
    	timer->portIdx=((etReplSubPort*)ifitem)->index;
    	getTimeFromTarget(&(timer->expTime));
    	addTime(&(timer->expTime),&t);
    	putTcbToUsedList(timer);
    	}
}
static void action_TRANS_tr3_FROM_Operational_TO_Operational_BY_startTimertimer_tr3(ATimingService* self, const InterfaceItemBase* ifitem, uint32 time) {
    etTimerControlBlock* timer = getTcb();
    etTime t;
    if (timer!= 0){
    	t.sec=time/1000;
    	t.nSec=(time%1000)*1000000L;
    	timer->pTime = t;
    	timer->portIdx=((etReplSubPort*)ifitem)->index;
    	getTimeFromTarget(&(timer->expTime));
    	addTime(&(timer->expTime),&t);
    	putTcbToUsedList(timer);
    	}
}
static void action_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4(ATimingService* self, const InterfaceItemBase* ifitem) {
    removeTcbFromUsedList(((etReplSubPort*)ifitem)->index);
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(ATimingService* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_Operational:
				self->history[STATE_TOP] = STATE_Operational;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(ATimingService* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__Operational:
		{
			action_TRANS_INITIAL_TO__Operational(self);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_startTimeouttimer_tr1:
		{
			uint32 time = *((uint32*) generic_data__et);
			action_TRANS_tr1_FROM_Operational_TO_Operational_BY_startTimeouttimer_tr1(self, ifitem, time);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_startTimertimer_tr3:
		{
			uint32 time = *((uint32*) generic_data__et);
			action_TRANS_tr3_FROM_Operational_TO_Operational_BY_startTimertimer_tr3(self, ifitem, time);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4:
		{
			action_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4(self, ifitem);
			return STATE_Operational;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(ATimingService* self, etInt16 state__et) {
	etBool skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_Operational:
				if (!(skip_entry__et)) entry_Operational(self);
				/* in leaf state: return state id */
				return STATE_Operational;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void ATimingService_executeInitTransition(ATimingService* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__Operational;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void ATimingService_receiveEventInternal(ATimingService* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = (ifitem==NULL)? POLLING : localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
		    case STATE_Operational:
		        switch(trigger__et) {
		            case POLLING:
		                do_Operational(self);
		                break;
		            case TRIG_timer__startTimeout:
		                {
		                    chain__et = CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_startTimeouttimer_tr1;
		                    catching_state__et = STATE_TOP;
		                }
		            break;
		            case TRIG_timer__startTimer:
		                {
		                    chain__et = CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_startTimertimer_tr3;
		                    catching_state__et = STATE_TOP;
		                }
		            break;
		            case TRIG_timer__kill:
		                {
		                    chain__et = CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4;
		                    catching_state__et = STATE_TOP;
		                }
		            break;
		            default:
		                /* should not occur */
		                break;
		        }
		        break;
		    default:
		        /* should not occur */
		        break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void ATimingService_receiveEvent(ATimingService* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	ATimingService_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void ATimingService_init(ATimingService* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ATimingService", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ATIMINGSERVICE_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	ATimingService_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ATimingService_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ATimingService", "_receiveMessage")
	ATimingService_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}

void ATimingService_execute(ATimingService* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("ATimingService", "_execute")

	ATimingService_receiveEvent(self, NULL, 0, NULL);

	ET_MSC_LOGGER_SYNC_EXIT
}

/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/
 void ATimingService_returnTcb(ATimingService* self, etTimerControlBlock* block) {
	block->next=freeTcbsRoot;
	freeTcbsRoot=block;
}
 void ATimingService_putTcbToUsedList(ATimingService* self, etTimerControlBlock* block) {
	etTimerControlBlock* temp=usedTcbsRoot;
	etTimerControlBlock* temp2=usedTcbsRoot;
	
	if (temp==0){
		/* list empty put new block to root */
		block->next=0;
		usedTcbsRoot=block;
		return;
		}
	
	while(1){
		if (temp != 0){
			if (isTimeGreater(&block->expTime,&temp->expTime)){
				/* try next position */
				temp2=temp;	
				temp=temp->next;
				}else{
				/* right position found */
				block->next=temp;
				if(temp==usedTcbsRoot){
					usedTcbsRoot=block;
					}else{
					temp2->next=block;
					}
				return;
				}
			}else{
			/* end of list reached */
			block->next=0;
			temp2->next=block;
			return;
		}
	}
}
 void ATimingService_addTime(ATimingService* self, etTime* t1, etTime* t2) {
	t1->sec += t2->sec;
	t1->nSec += t2->nSec;
	while(t1->nSec >= 1000000000L){
		t1->sec++;
		t1->nSec-=1000000000L;
	}
}
 etTimerControlBlock* ATimingService_getTcb(ATimingService* self) {
	etTimerControlBlock* temp = freeTcbsRoot;
	
	if(freeTcbsRoot!=0) {
		freeTcbsRoot=freeTcbsRoot->next;
		temp->next=0;
		}
	return temp;
}
 void ATimingService_removeTcbFromUsedList(ATimingService* self, int32 idx) {
	etTimerControlBlock* temp=usedTcbsRoot;
	etTimerControlBlock* temp2=usedTcbsRoot;
	
	if (temp==0) return;
	
	if (usedTcbsRoot->portIdx == idx){
		/* element found, the first one */
		usedTcbsRoot = usedTcbsRoot->next;
		returnTcb(temp);
		return;
	}
	
	temp=temp->next;
	while(temp!=0){
		if(temp->portIdx==idx){
			temp2->next=temp->next;
			returnTcb(temp);
			return;			
		}else{
			/* try next */
			temp2=temp;
			temp=temp->next;
			}
	}
}
 bool ATimingService_isTimeGreater(ATimingService* self, etTime* t1, etTime* t2) {
	if (t1->sec > t2->sec) return ET_TRUE;
	if (t1->sec < t2->sec) return ET_FALSE;
	if (t1->nSec > t2->nSec) return ET_TRUE;
	return ET_FALSE;
}

