/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTimer
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TIMING_PTIMER_UTILS_H_
#define _ROOM_BASIC_SERVICE_TIMING_PTIMER_UTILS_H_

#include "room/basic/service/timing/PTimer.h"

/*
 * access macros for operations and attributes
*/

/* conjugate port class */

/* operations */

/* attributes */
#define status (((PTimerConjPort_var*)(self->varData))->status)

#endif /* _ROOM_BASIC_SERVICE_TIMING_PTIMER_UTILS_H_ */

