/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass ATcpClient
 *
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_ATCPCLIENT_UTILS_H_
#define _ROOM_BASIC_SERVICE_TCP_ATCPCLIENT_UTILS_H_

#include "room/basic/service/tcp/ATcpClient.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define controlPort_connected() PTcpControlPort_connected(&self->constData->controlPort)
#define controlPort_disconnected() PTcpControlPort_disconnected(&self->constData->controlPort)
#define controlPort_error() PTcpControlPort_error(&self->constData->controlPort)
#define payloadPort_dataPackage(data) PTcpPayloadPort_dataPackage(&self->constData->payloadPort, data)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */
#define hasError() ATcpClient_hasError(self)
#define setErrorCode(value) ATcpClient_setErrorCode(self, value)

/* attributes */
#define lastError (self->lastError)
#define payloadRecvBuffer (self->payloadRecvBuffer)
#define client (self->client)

/* port operations */

#endif /* _ROOM_BASIC_SERVICE_TCP_ATCPCLIENT_UTILS_H_ */

