/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PTcpPayload
 * 
 */

#include "PTcpPayload.h"
#include "debugging/etMSCLogger.h"
#include "PTcpPayload_Utils.h"


/*--------------------- port methods */

void PTcpPayloadPort_dataPackage(const PTcpPayloadPort* self, DTcpPayload* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadPort", "dataPackage")
		etPort_sendMessage(self, PTcpPayload_OUT_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "dataPackage", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTcpPayloadReplPort_dataPackage_broadcast(const PTcpPayloadReplPort* self, DTcpPayload* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadReplPort", "dataPackage")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PTcpPayload_OUT_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "dataPackage", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTcpPayloadReplPort_dataPackage(const PTcpPayloadReplPort* self, int idx__et, DTcpPayload* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadReplPort", "dataPackage")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PTcpPayload_OUT_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "dataPackage", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PTcpPayloadReplPort_getReplication(const PTcpPayloadReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PTcpPayloadConjPort_dataPackage(const PTcpPayloadConjPort* self, DTcpPayload* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadConjPort", "dataPackage")
		etPort_sendMessage(self, PTcpPayload_IN_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "dataPackage", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTcpPayloadConjReplPort_dataPackage_broadcast(const PTcpPayloadConjReplPort* self, DTcpPayload* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadConjReplPort", "dataPackage")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PTcpPayload_IN_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "dataPackage", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PTcpPayloadConjReplPort_dataPackage(const PTcpPayloadConjReplPort* self, int idx__et, DTcpPayload* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PTcpPayloadConjReplPort", "dataPackage")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PTcpPayload_IN_dataPackage, sizeof(DTcpPayload), data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "dataPackage", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PTcpPayloadConjReplPort_getReplication(const PTcpPayloadConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */

/* message names as strings for debugging (generate MSC) */
static const char* const PTcpPayload_messageStrings[] = {"MIN", "dataPackage","dataPackage", "MAX"};

const char* PTcpPayload_getMessageString(int msg_id) {
	if (msg_id<PTcpPayload_MSG_MIN || msg_id>PTcpPayload_MSG_MAX+1){
		/* id out of range */
		return "Message ID out of range";
	}
	else{
		return PTcpPayload_messageStrings[msg_id];
	}
}
