/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTcpPayload
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_TCP_PTCPPAYLOAD_UTILS_H_
#define _ROOM_BASIC_SERVICE_TCP_PTCPPAYLOAD_UTILS_H_

#include "room/basic/service/tcp/PTcpPayload.h"

/*
 * access macros for operations and attributes
*/


#endif /* _ROOM_BASIC_SERVICE_TCP_PTCPPAYLOAD_UTILS_H_ */

