/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass ATimingService
 *
 */

#ifndef _ROOM_BASIC_SERVICE_TIMING_ATIMINGSERVICE_UTILS_H_
#define _ROOM_BASIC_SERVICE_TIMING_ATIMINGSERVICE_UTILS_H_

#include "room/basic/service/timing/ATimingService.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */
#define timer_timeout_broadcast() PTimerReplPort_timeout_broadcast(&self->constData->timer)
#define timer_timeout(idx) PTimerReplPort_timeout(&self->constData->timer, idx)

/* operations */
#define returnTcb(block) ATimingService_returnTcb(self, block)
#define putTcbToUsedList(block) ATimingService_putTcbToUsedList(self, block)
#define addTime(t1, t2) ATimingService_addTime(self, t1, t2)
#define getTcb() ATimingService_getTcb(self)
#define removeTcbFromUsedList(idx) ATimingService_removeTcbFromUsedList(self, idx)
#define isTimeGreater(t1, t2) ATimingService_isTimeGreater(self, t1, t2)

/* attributes */
#define tcbs (self->tcbs)
#define usedTcbsRoot (self->usedTcbsRoot)
#define freeTcbsRoot (self->freeTcbsRoot)

/* port operations */

#endif /* _ROOM_BASIC_SERVICE_TIMING_ATIMINGSERVICE_UTILS_H_ */

