/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AccelPedalDiagEntity
 *
 */

#ifndef _TEMPLATEMODEL_ACCELPEDALDIAGENTITY_H_
#define _TEMPLATEMODEL_ACCELPEDALDIAGENTITY_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec diagstart,diagend;
FILE *fp;
/*--------------------- end user code ---------------------*/

typedef struct AccelPedalDiagEntity AccelPedalDiagEntity;

/* const part of ActorClass (ROM) */
typedef struct AccelPedalDiagEntity_const {
	const char* instName;

	/* simple ports */

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} AccelPedalDiagEntity_const;


/* constant for state machine data */
#define ACCELPEDALDIAGENTITY_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AccelPedalDiagEntity {
	const AccelPedalDiagEntity_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int64 count;
	 int32 actor4_1_id;


	/* state machine variables */
	etInt16 state;
	etInt16 history[ACCELPEDALDIAGENTITY_HISTORY_SIZE];
};

void AccelPedalDiagEntity_init(AccelPedalDiagEntity* self);

void AccelPedalDiagEntity_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_ACCELPEDALDIAGENTITY_H_ */

