/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AccelPedalSensor
 *
 */

#ifndef _TEMPLATEMODEL_ACCELPEDALSENSOR_H_
#define _TEMPLATEMODEL_ACCELPEDALSENSOR_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec pedalsensestart,pedalsenseend;
/*--------------------- end user code ---------------------*/

typedef struct AccelPedalSensor AccelPedalSensor;

/* const part of ActorClass (ROM) */
typedef struct AccelPedalSensor_const {
	const char* instName;

	/* simple ports */
	const SendDataConjPort pedaldata;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} AccelPedalSensor_const;


/* constant for state machine data */
#define ACCELPEDALSENSOR_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AccelPedalSensor {
	const AccelPedalSensor_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int64 count;


	/* state machine variables */
	etInt16 state;
	etInt16 history[ACCELPEDALSENSOR_HISTORY_SIZE];
};

void AccelPedalSensor_init(AccelPedalSensor* self);

void AccelPedalSensor_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_ACCELPEDALSENSOR_H_ */

