/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass BassFuelMassEntity2
 *
 */

#ifndef _TEMPLATEMODEL_BASSFUELMASSENTITY2_UTILS_H_
#define _TEMPLATEMODEL_BASSFUELMASSENTITY2_UTILS_H_

#include "TemplateModel/BassFuelMassEntity2.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define bassfueldata2_recursive2(data) SendDataPort_recursive2(&self->constData->bassfueldata2, data)
#define bassfueldata2_recvchangestate() SendDataPort_recvchangestate(&self->constData->bassfueldata2)
#define bassfueldatasend2_sendData(data) SendDataConjPort_sendData(&self->constData->bassfueldatasend2, data)
#define bassfueldatasend2_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->bassfueldatasend2)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TEMPLATEMODEL_BASSFUELMASSENTITY2_UTILS_H_ */

