/**
 * @author generated by eTrice
 *
 * Header File of ActorClass FuelingSystem
 *
 */

#ifndef _TEMPLATEMODEL_FUELINGSYSTEM_H_
#define _TEMPLATEMODEL_FUELINGSYSTEM_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

/* include all referenced room classes */
#include "room/basic/service/timing/PTimer.h"
#include "TemplateModel/SendData.h"

/*--------------------- begin user code ---------------------*/
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <ctype.h>
struct timespec fuelstart2,fuelstart,fuelend,airsensestart,airsenseend;
FILE *fp5;
/*--------------------- end user code ---------------------*/

typedef struct FuelingSystem FuelingSystem;

/* const part of ActorClass (ROM) */
typedef struct FuelingSystem_const {
	const char* instName;

	/* simple ports */
	const SendDataPort airflowPort;
	const SendDataConjPort injectiondata;
	const SendDataConjPort fuelingInternalIn;
	const SendDataPort fuelingInternalOut;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} FuelingSystem_const;


/* constant for state machine data */
#define FUELINGSYSTEM_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct FuelingSystem {
	const FuelingSystem_const* const constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 float64 recvairflowsensetime;
	 float64 recvfirsttime;
	 int32 airflowemer;
	 int64 airflowscen;
	 int64 airflowins;
	 int64 count;
	 float64 tempairflowsensetime;
	 float64 tempfirsttime;
	 int32 actor3_1_id;
	 int32 actor3_2_id;


	/* state machine variables */
	etInt16 state;
	etInt16 history[FUELINGSYSTEM_HISTORY_SIZE];
};

void FuelingSystem_init(FuelingSystem* self);

void FuelingSystem_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_FUELINGSYSTEM_H_ */

