/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass InjectionActuator
 *
 */

#ifndef _TEMPLATEMODEL_INJECTIONACTUATOR_UTILS_H_
#define _TEMPLATEMODEL_INJECTIONACTUATOR_UTILS_H_

#include "TemplateModel/InjectionActuator.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define injectionPort_recursive2(data) SendDataPort_recursive2(&self->constData->injectionPort, data)
#define injectionPort_recvchangestate() SendDataPort_recvchangestate(&self->constData->injectionPort)
#define cylinerData_sendData(data) SendDataConjPort_sendData(&self->constData->cylinerData, data)
#define cylinerData_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->cylinerData)
#define injectionactorInternalIn_sendData(data) SendDataConjPort_sendData(&self->constData->injectionactorInternalIn, data)
#define injectionactorInternalIn_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->injectionactorInternalIn)
#define injectionactorInternalOut_recursive2(data) SendDataPort_recursive2(&self->constData->injectionactorInternalOut, data)
#define injectionactorInternalOut_recvchangestate() SendDataPort_recvchangestate(&self->constData->injectionactorInternalOut)

/* data receive ports */

/* data send ports */

/* saps */
#define timer_startTimer(data) PTimerConjPort_startTimer(&self->constData->timer, data)
#define timer_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->timer, data)
#define timer_kill() PTimerConjPort_kill(&self->constData->timer)

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define recvscenarioID (self->recvscenarioID)
#define recvinstanceID (self->recvinstanceID)
#define recvemer (self->recvemer)
#define count (self->count)
#define count2 (self->count2)
#define recvfuelingsystemtime (self->recvfuelingsystemtime)
#define recvfuelingsystemtime2 (self->recvfuelingsystemtime2)
#define recvcylinertime (self->recvcylinertime)
#define recvairmasstime (self->recvairmasstime)
#define recvbassairtime (self->recvbassairtime)
#define recvtransientfueltime (self->recvtransientfueltime)
#define recvtotalfueltime (self->recvtotalfueltime)
#define recvinjectionactuatortime (self->recvinjectionactuatortime)
#define injectionacttime (self->injectionacttime)
#define injectionacttime2 (self->injectionacttime2)
#define injectionacttime3 (self->injectionacttime3)
#define injectionstarttime (self->injectionstarttime)
#define actor6_1_id (self->actor6_1_id)
#define actor6_2_id (self->actor6_2_id)
#define actor6_3_id (self->actor6_3_id)
#define actor6_4_id (self->actor6_4_id)
#define actor6_5_id (self->actor6_5_id)
#define actor6_6_id (self->actor6_6_id)
#define actor9_1_id (self->actor9_1_id)
#define actor9_2_id (self->actor9_2_id)
#define actor9_3_id (self->actor9_3_id)
#define actor9_4_id (self->actor9_4_id)
#define actor9_5_id (self->actor9_5_id)
#define actor9_6_id (self->actor9_6_id)

/* port operations */

#endif /* _TEMPLATEMODEL_INJECTIONACTUATOR_UTILS_H_ */

