/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass TopActor
 *
 */

#ifndef _TEMPLATEMODEL_TOPACTOR_UTILS_H_
#define _TEMPLATEMODEL_TOPACTOR_UTILS_H_

#include "TemplateModel/TopActor.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TEMPLATEMODEL_TOPACTOR_UTILS_H_ */

