/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass TransientFuelingCompensationEntity
 *
 */

#ifndef _TEMPLATEMODEL_TRANSIENTFUELINGCOMPENSATIONENTITY_UTILS_H_
#define _TEMPLATEMODEL_TRANSIENTFUELINGCOMPENSATIONENTITY_UTILS_H_

#include "TemplateModel/TransientFuelingCompensationEntity.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define transientfueldata_recursive2(data) SendDataPort_recursive2(&self->constData->transientfueldata, data)
#define transientfueldata_recvchangestate() SendDataPort_recvchangestate(&self->constData->transientfueldata)
#define transientfueldatasend_sendData(data) SendDataConjPort_sendData(&self->constData->transientfueldatasend, data)
#define transientfueldatasend_sendchangestate() SendDataConjPort_sendchangestate(&self->constData->transientfueldatasend)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _TEMPLATEMODEL_TRANSIENTFUELINGCOMPENSATIONENTITY_UTILS_H_ */

